version: '3.8'

services:
  next-app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app            # While updading the code in the pc automatic update will be done in the docker container
      - /app/node_modules # Avoid the node_modules folder confilct with the docker node_modules
    environment:
      - NODE_ENV=development